-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.classroom
(
    id integer NOT NULL DEFAULT nextval('classroom_id_seq'::regclass),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    "tutorIdId" integer,
    tutor_id integer NOT NULL,
    CONSTRAINT "PK_729f896c8b7b96ddf10c341e6ff" PRIMARY KEY (id),
    CONSTRAINT "UQ_321e9ff53b2d2b374d6e8d3df8e" UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.classroom_files
(
    id integer NOT NULL DEFAULT nextval('classroom_files_id_seq'::regclass),
    file_id integer,
    tutor_id integer,
    classroom_id integer,
    CONSTRAINT "PK_5c5fec8c7e560a3502e3da4f18c" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.classroom_students
(
    id integer NOT NULL DEFAULT nextval('classroom_students_id_seq'::regclass),
    classroom_id integer NOT NULL,
    student_id integer NOT NULL,
    CONSTRAINT "PK_db3107d9dfc068f81fc585ec554" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.file
(
    id integer NOT NULL DEFAULT nextval('file_id_seq'::regclass),
    uploaded_by integer,
    classroom_id integer,
    url character varying COLLATE pg_catalog."default" NOT NULL,
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    description character varying(300) COLLATE pg_catalog."default" NOT NULL,
    "uploadedAt" timestamp without time zone NOT NULL DEFAULT now(),
    "fileType" character varying COLLATE pg_catalog."default" NOT NULL,
    "fileDetails" json,
    CONSTRAINT "PK_36b46d232307066b3a2c9ea3a1d" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."user"
(
    id integer NOT NULL DEFAULT nextval('user_id_seq'::regclass),
    username character varying COLLATE pg_catalog."default" NOT NULL,
    password character varying COLLATE pg_catalog."default" NOT NULL,
    role user_role_enum NOT NULL,
    CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY (id),
    CONSTRAINT "UQ_78a916df40e02a9deb1c4b75edb" UNIQUE (username)
);

ALTER TABLE IF EXISTS public.classroom
    ADD CONSTRAINT "FK_96251724994e984be7944f697db" FOREIGN KEY ("tutorIdId")
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.classroom_files
    ADD CONSTRAINT "FK_1b100c4c995dc95ae9e8523b898" FOREIGN KEY (classroom_id)
    REFERENCES public.classroom (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.classroom_files
    ADD CONSTRAINT "FK_b621b326a4ae454bfc6dc897c91" FOREIGN KEY (file_id)
    REFERENCES public.file (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.classroom_files
    ADD CONSTRAINT "FK_c99cb154c005bbdc451f9163046" FOREIGN KEY (tutor_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.classroom_students
    ADD CONSTRAINT "FK_5a5c9a209121e443814e35c3778" FOREIGN KEY (classroom_id)
    REFERENCES public.classroom (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.classroom_students
    ADD CONSTRAINT "FK_74e55b9a7309bdab5e8f53672db" FOREIGN KEY (student_id)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.file
    ADD CONSTRAINT "FK_2c232bcf7b6720c62e70c09f06f" FOREIGN KEY (classroom_id)
    REFERENCES public.classroom (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.file
    ADD CONSTRAINT "FK_7b877394007233a988b1b845378" FOREIGN KEY (uploaded_by)
    REFERENCES public."user" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;